pub const HTML_STRINGS: [&str; 20] = [
    r#"<html><body><h1>Hello, World!</h1></body></html>"#,
    r#"<html><body><p>This is a paragraph.</p></body></html>"#,
    r#"<html><body><ul><li>Item 1</li><li>Item 2</li></ul></body></html>"#,
    r#"<html><body><ol><li>Item 1</li><li>Item 2</li></ol></body></html>"#,
    r#"<html><body><table><tr><td>Cell 1</td><td>Cell 2</td></tr></table></body></html>"#,
    r#"<html><body><div>This is a div.</div></body></html>"#,
    r#"<html><body><span>This is a span.</span></body></html>"#,
    r#"<html><body><button>This is a button.</button></body></html>"#,
    r#"<html><body><input type="text" placeholder="This is an input field." /></body></html>"#,
    r#"<html><body><select><option>Option 1</option><option>Option 2</option></select></body></html>"#,
    r#"<html><body><textarea>This is a textarea.</textarea></body></html>"#,
    r#"<html><body><svg>This is an SVG.</svg></body></html>"#,
    r#"<html><body><nav>This is a nav.</nav></body></html>"#,
    r#"<html><body><footer>This is a footer.</footer></body></html>"#,
    r#"<html><body><header>This is a header.</header></body></html>"#,
    r#"<html><body><main>This is a main.</main></body></html>"#,
    r#"<html><body><section>This is a section.</section></body></html>"#,
    r#"<html><body><article>This is an article.</article></body></html>"#,
    r#"<html><body><aside>This is an article.</aside></body></html>"#,
    r#"<html><body><h2>This is an article.</h2></body></html>"#,
];
